apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: 'prometheus-ds' # <-- Añadimos este ID estático
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false